# Generated by Django 4.1.2 on 2022-10-12 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(unique=True, verbose_name=django.core.validators.MaxValueValidator(100))),
            ],
        ),
    ]
